### ISSUE TITLE
Error unzipping the prebuilt runtime files

### ISSUE THREAD

**Issue by michhar** [vjrantal/iot-edge-darknet-module#12]
Hi, this is a great project, thanks for updating to latest IoT Edge GA.

I download the zipped packages with `wget` (tried `curl` as well).  I get this error (run on the PX2 w/ Ubuntu 16.04):

(I feel like I'm missing a simple piece and help appreciated).

```
Archive:  iotedge-libiothsm-std-aarch64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of iotedge-libiothsm-std-aarch64.zip or
        iotedge-libiothsm-std-aarch64.zip.zip, and cannot find iotedge-libiothsm-std-aarch64.zip.ZIP, period.
```

**Comment by vjrantal** [comment]
@michhar Thanks for the interest towards the project!

I was able to download and unzip on Jetson TX2. Here https://gist.github.com/vjrantal/2b6fa9273330adf5673c9c3fe232e719 is output of the commands I run.

I have to say I don't know what is the issue on your side, but perhaps you can try downloading and unzipping on some other platform (such as on your desktop machine) and then copying the .deb files to the PX2?

**Comment by michhar** [comment]
@vjrantal  Thanks for the info in your gist!  Interestingly, I ran into trouble inflating it on my Windows desktop yesterday as well as the PX2 running Ubuntu.  It appears to have been a bad download on both.  Only received a 585b file.  With a reboot of the PX2 and trying this download/unarchiving again, all is well!

**Comment by vjrantal** [comment]
@michhar Great to hear this got resolved!
